- themes/pcsx2/layouts/_default/baseof.html
Images for the comparison sliders have to have their `height`s manipulated for the rest of the styling/elements around them to layout properly.
Because of this, the aspect ratio is not preserved.  This assumes both images are the same (they should be for comparison sliders...) and manually sets the aspect ratio on the containing div.
> theme: adjust aspect ratios on image comparison sliders

- content/guides/basic-setup/index.md
In Basic Setup Guide
* explain the steps, and the intermediate uLaunchELF
* replace 'mod your PS2' with '"hack" your PS2'
* explain which methods boot into uLaunchELF
* add step of extracting PS2dumper files to USB afte downloading them.
* move USB format recommendation to this step.
* mention FAT32 vs. exFAT file formats for USB flash drive
* only mention DVD-R recommendations once.
* describe what happens during PS2 dumper operation.
> Improve BIOS dumping instructions

- .vscode/extensions.json
- .vscode/settings.json
- Taskfile.yml
- content/guides/basic-setup/index.md
- cspell.json
Not adding to CI as the false positives in our situation will be quite high, we'll just always having a failing job.
But adds extension recommendations to get spellchecking locally and a sample command to run it on all markdown files.  Running it on one would look something like:
`npx cspell content/**/new-website/*.md`
> tools: add some basic spellcheck configuration

- themes/pcsx2/layouts/_default/baseof.html
You get issues that it caches old version of the charts file when for example using the preview site and when it goes live you don't have the correct latest version.
This should force it to not be cached for users which is helpful for future fixes or additions to older progress reports.
> Q4-2021: Force charts javascript version

- config.yaml
- content/guides/basic-setup/index.md
- tests/cypress/integration/components/navbar_spec.js
- themes/pcsx2/assets/sass/_articles.sass
Also adds aliases from the old `/getting-started`, `/config-guide/guide-translations` and `/download/releases/tools` links to this page.
Closes #89 
Closes #84
> guide: add requirements and config info to setup guide

- content/guides/basic-setup/index.md
Just some small things i noticed in the previous PR (mostly just a mistake during conflict resolution I think) -- easier to just follow up with a fix.
> docs: fix up biosdrain docs and image sizes

- src/pages/index.js
It's not perfect behavior wise (the tooltip will come back when the dropdown is clicked away from).  But this ultimately is a temporary warning that will go away when the next stable is launched, and the positioning doesn't get in the way.
> downloads: add a tooltip on the homepage encouraging nightly usage

- docusaurus.config.js
Avoids an redirect message when clicking on "Edit this document".
> Docs: Fix Github URLs for editing

- docs/usage/setup/index.md
Was still mentioning 1600/2100 instead of 1800/2600 and pointing to outdated pre-v1 translation guides on the forum that are bare-bones will not help anyone, so point to Crowdin.
> Setup guide - min/recommended specs + Crowdin

- package.json
- yarn.lock
Reverts PCSX2/pcsx2-net-www#245
Show Previous Versions might be broken by this.
> Revert "build(deps): bump @docusaurus/plugin-client-redirects from 2.3.1 to 2.4.1"

- src/components/ReleaseDownloadButton/index.js
Stable just shows 32bit, whilst the Nightly says Appimage - x64 Qt
Stable:
Nightly:
> DownloadButton: Fix stable AppImage not showing

- src/components/ReleaseDownloadButton/index.js
It looks off compared to the Linux side that looks cleaner when you download releases on pcsx2.net. Revising from
into
> DownloadButton: Fix formatting Windows, Linux and Apple

- src/pages/downloads/index.js
Forgot to change it when we moved the docs link
> Fix broken link on Downloads page

- src/css/custom.css
- src/theme/BlogPostItem/Header/index.js
Adds a titleImage property to MDX that allows the writer to have a title background on the post, as seen below.
If unused, reverts to the previous styling.
We should:
(Added some drop shadow for styling)
Add a `titleImage` to any blog post metadata, pointing to the `static/img` folder
> BlogPostItem: add titleImage styling in prevision of 2.0

- src/css/custom.css
This fixes a few issues I picked up on when using the white theme with the new titleImage styling
before:
now:
NB: might be interesting to check whether we can "invert" the titleImage card like the homepage animation to fully conform to the white theme...
> misc white theme title fixes

- .gitignore
This PR cleans up useless yarn.lock and package.json files as they are automatically generated when you do `npm install`
> gitignore: ignore autogenerated yarn deps files

- docs/usage/setup/gather.md
I was informed that someones modchip clone caused their bios dump to have no OSDSYS.
I also added a mention to the Fortuna exploit which is essentially FMCB for all slims.
> Gather: Add modchip warning, mention fortuna exploit

- docs/setup/requirements.md
Just a bit of cleanup 2 electric boogaloo
> Update system requirements

- src/pages/downloads/index.js
We found out that Poper Blocker is breaking downloads on our site, so add a warning to the page for users to disable it.
> Download: Add warning about Poper Blocker

- config.yaml
- docs/index.md
- docs/troubleshooting/identify.md
- docusaurus.config.js
- redirects.js
Credit to @GovanifY for giving me the idea and to @kamfretoz for pointing out that there's an easy way to do redirects. :smile: 
This makes it so that 1) we and anyone else can easily reproduce the link from memory because it's not a string of random characters, and importantly 2) if the invite link ever does change, we don't ever need to go cleaning things up except to change it in the `redirects.js` file.
> Redirects: Create pcsx2.net/discord

- src/components/ReleaseDownloadButton/index.js
> styling: fix download link colors when on light-mode

- docs/advanced/debugger.md
I was having another read through it and I noticed the version numbers in the symbol table support table were wrong, as well as a couple typos.
> Docs: Fix some issues with the debugger documentation

- src/components/DownloadTable/index.js
Total needs to be stateful in order to tell the Pagination element to update its presentation, otherwise it will create arrows where it shouldn't which might lead to jumping into undefined territory (literally)
This fixes https://github.com/PCSX2/pcsx2-net-www/issues/401
> DownloadTable: make totalTable stateful and fix NaN bug

- src/pages/downloads/index.js
When you refreshed the download page while previously allowing default versions, it would show them by default BUT render the switch as unchecked, let's fix that.
> downloads: make sure dl switch is defaulting to the localStorage

- docusaurus.config.js
This is an initiative for the preservation of video games, available here:
https://eci.ec.europa.eu/045/public/#/screen/home
Dolphin already links to it and now that the ban on conversion therapy (yay!) passed the threshold I got reminded of this one, let's try to give it a push with our reach :)
> config: add banner for stop killing games

- blog/2025/pcsx2-2.4_2.2/index.mdx
Text was never properly removed from the blog before it was pushed to prod.
> Blog: Fix accidental copy-paste placeholder which was never removed

- docs/advanced/building.md
This adds a small section to the bottom of the build guide about our GammaRay build scripts. I [added these a while back](https://github.com/PCSX2/pcsx2/pull/12449) to make working on the UI a little easier, this should help people actually find them.
> Docs: Add a section about the GammaRay build scripts to the build guide

- docusaurus.config.js
Stop Destroying Videogames EU initiative is no longer active and thus users cannot sign the petition. No need for the current banner anymore.
> Banner: Remove SDVG EU initiative announcement as petition is closed
