PCSX2/pcsx2-net-www

.github/scripts/check-for-pngs.py, .github/workflows/build.yaml, README.md, docs/shortcodes.md, themes/pcsx2/layouts/_default/_markup/render-link.html, themes/pcsx2/layouts/partials/navbar.html
Also added some docs
Closes #27
=> ci: Add some basic CI workflows that verify the build

themes/pcsx2/static/js/release-page.js
=> downloads: improve the tooltips for when no release is found

content/downloads.md, themes/pcsx2/assets/sass/_general.sass, themes/pcsx2/assets/sass/_releases.sass, themes/pcsx2/layouts/page/downloads.html, themes/pcsx2/layouts/partials/downloads/skeleton-table.html, themes/pcsx2/static/js/release-page.js
=> downloads: add MacOS latest release buttons

docs/shortcodes.md, themes/pcsx2/assets/sass/_articles.sass, themes/pcsx2/layouts/shortcodes/img-cmp.html
=> shortcode: add label to non-slider image compare

content/blog/2020/q3-2020-progress-report/index.md, content/blog/2020/q4-2020-progress-report/index.md, content/blog/2021/q1-2021-progress-report/index.md, content/blog/2021/q2-2021-progress-report/index.md, content/blog/2021/q3-2021-progress-report/index.md, content/blog/2022/q4-2021-progress-report/index.md, content/guides/basic-setup/index.md
General clean-up of the website, I also wanted to change the description of the stable releases but I can't as it has a permanent tag on pcsx2 archive.
=> Web: Typos, metadata progress report, BIOS guide

static/ads.txt
Needed by Google https://support.google.com/adsense/answer/7532444?hl=en
=> assets: add `ads.txt` file

config.yaml, themes/pcsx2/layouts/_default/single.html, themes/pcsx2/layouts/partials/head.html
Adds last modified date + commit comment, and Related Posts under the content of the post:
Closes #132 
Closes #17 
Closes #73
=> Add Last Updated and Related to bottom of posts. Expose RSS feeds.

content/guides/basic-setup/index.md
Updates the spec requirements to match the change to nightlys.
=> Update spec requirements in line with recent changes

content/blog/2010/the-history-of-pcsx2/index.md
=> Fixes to 'The History Of PCSX2'

src/components/ReleaseDownloadButton/index.js
Removes fade in/out on dropdown menu highlights, which makes them feel much more responsive
=> Improve responsiveness of dropdown menus

.github/workflows/build.yaml
Just fixes the typo when the workflow file is busy, no real change to website.
=> deps: Depdencies to Depencies

package.json, yarn.lock
This reverts commit 89bee379470e9e78e9aa3628e0842b246ff8bcd8.
Should fix older build downloads
=> Revert "build(deps):w.unified (216?)"

.github/workflows/update-compat.yaml, package.json, yarn.lock
…4.2.4 (#213)"
This reverts commit 7ff99d64e14c73403cd2858cdea50c4a06bff68b.
… to 2.4.0 (#214)"
This reverts commit 3859126b81a545a74337df320b51719a8b0dce31.
(#215)
This reverts commit 27b8bfc637220bd492a73b81d27475c8ec04d892.
=> Revert "build(deps): bump react-icons from 4.7.1 to 4.8.0 (#215)"

src/components/ReleaseDownloadButton/index.js
It only says Download on any stable Windows download which isn't a good look.
PR 257 did this:
New Fix:
=> DownloadButton: Fix Installer and Portable Windows

docs/troubleshooting/windows.md, docs/usage/setup/requirements.md
=> update URL for ffmpeg

docs/usage/setup/requirements.md
Also a small bit of cleanup of other minor things.
=> Update system requirements

src/components/ReleaseDownloadButton/index.js, src/pages/index.js
Just an idea.
I wanted to quickly PR it because I have to sleep. Close it if it's not liked.
=> Index: Disable the stable build download button

.gitignore
This reverts commit beca7d9ea64c965f92dbef91de4eb14a5fed0166.
=> Revert "gitignore: ignore autogenerated yarn deps files (#298)"

docs/post/general.md, docs/setup/linux.md
Just small fixes and add more details.
=> Docs: Small Hotfixes

docs/post/cli.md, docs/post/controllers.md, docs/post/general.md, docs/setup/linux.md, docs/troubleshooting/windows.md
Adds Buzz controller to controller and few fixes here and there.
=> Docs: Update and Fixes

docusaurus.config.js
Was done here but that hasn't merged yet https://github.com/PCSX2/pcsx2-net-www/pull/283
=> docusaurus: default to smaller preview card image

docusaurus.config.js
=> rss: limit feed to 3 articles

docusaurus.config.js, src/css/custom.css
Following the discussion with TheTechnician27, I replaced our main SNS from twitter to mastodon.
Don't merge yet, haven't tested if the icon looks fine, will wait on cloudflare to see
=> socials: replace twitter by mastodon

.github/workflows/build.yaml, blog/2021/q3-2021-progress-report/index.mdx, blog/2022/q4-2021-progress-report/index.mdx, blog/2023/q1-2022-progress-report/index.mdx, docs/post/controllers.md, package.json, yarn.lock
Update DsHidMini link to the new site
=> Docs: Update link to Nefarius's new DsHidMini site

docs/troubleshooting/general.md, docs/troubleshooting/windows.md
Update the ffmpeg troubleshooting section with instructions and moving it to the General troubleshooting section.
=> Docs: Update ffmpeg troubleshooting section

docs/index.md, docs/setup/bios.md, docs/setup/dumping.md, docs/setup/linux.md, docs/setup/requirements.md, docs/setup/windows.md
Proofreads the current setup guides. A future PR will add a macOS setup guide.
=> Docs: Proofread setup guides

docusaurus.config.js
We are MIT, we don't reserve all rights, but we DO preserve our copyright.
=> config.js: remove mention of rights reserved

src/pages/index.js
=> index: fix typo on description

docs/advanced/building.md, docs/contributing/contributing.md, docs/post/general.md, docs/troubleshooting/identify.md
Add Xcode requirements for mac, and fixed some details
=> Docs: Some tweaks and additions

blog/2025/pcsx2-2.4_2.2/index.mdx, src/data/latestBlogs.js
=> Blog: Update latest blog post list

docs/post/controllers.md
Did a pass over the controllers doc and rewrote significant portions of it to address updated info, missing info, grammar, etc.
Should help explain some elements of controllers which are frequently asked about. Also will allow us to better hotlink out to this doc from Discord.
=> Rewrite entire controller article for grammar/spelling/clarity

docs/setup/requirements.md, package.json, yarn.lock
System requirements are currently laid out in a long list of nested bullet points. This PR places them into an easily parsed table. The benefits are as follows:
* Relevant data are presented alongside each other. For example, on a 16:9 desktop, I could not compare the minimum rec CPU with the moderate rec CPU without scrolling. Here, they are directly adjacent, as are all other components of the rec.
* Vertical scroll distance is reduced despite more information by better utilizing horizontal space.
* Much cleaner aesthetically, especially as a first impression for our docs.
* Able to combine the various notes spread throughout the recs into a single cohesive 'INFO' box beneath the table.
* Able to place example hardware into its own companion table for easier viewing.
@TellowKrinkle …
=> Docs: Overhaul System Requirements page
